// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndgnqiwdhqmviharrqqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZ25xaXdkaHFtdmloYXJycXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTQ3NzQsImV4cCI6MjA2NjAzMDc3NH0.EIhU1IGLXw0n_vgSoXok9KFQDTTLSrqW_N8ucJ_40Ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
